### ISSUE TITLE
Confusion of output

### ISSUE THREAD

**Issue by Edison2021** [ncbi/magicblast#11]
Hi 
The manual ( https://ncbi.github.io/magicblast/doc/output.html) mentions that the 12th column is not used in the output. However, i found a value at this position.

cds      0        100      0        0        0        1        357      1        512      0        99       357      plus     plus     357      64^75^160^80^133         1        -        1:0     -        -        -        -        357

Could you help explain what do 12th  and 13th columns mean?

Edison

**Comment by boratyng** [comment]
Hi Edison, 
    The 13th column is used, it is alignment score. Columns 11th and 12th are not used. These are always zero and 99. 

The unused columns are meant for the first 12 columns to look like tabular output from blastn, so that a few Magic-BLAST alignments can be piped into Splign (https://www.ncbi.nlm.nih.gov/sutils/splign/splign.cgi), which can compute more accurate alignments. Unfortunately due to changes in splign this functionality no longer works seamlessly and Splign can only handle a few alignments.

Also, we cannot remove the unused columns, because that would change location of other columns and break users' pipelines. We are working on a better tabular format for Magic-BLAST where one would be able to select columns and their order.

**Comment by Edison2021** [comment]
Thanks! Grzegorz!
